# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxvP438WFKcXtcjS1GToJMrXjTxlFv6i
"""

## Invoking the Interpreter
print("Interpreter is running!")
import platform
print(platform.python_version())

## Operators
x, y = 15, 4
print(x + y)   # 19
print(x - y)   # 11
print(x * y)   # 60
print(x / y)   # 3.75
print(x // y)  # 3
print(x % y)   # 3
print(x ** y)  # 50625
print(x < y, x >= y, x == 15)
print(not (x < y))   # logical NOT

## Strings
s = "Python Programming"
print(s.lower())
print(s.upper())
print(s.startswith("Python"))
print(s[7:])          # slicing from index 7
print(s.count("m"))
print(" ".join(["Data", "Science", "Rocks"]))
lang = "Python"
version = 3
print(f"{lang} version {version} is powerful")

## Dir and Help
nums = [1, 2, 3]
print(dir(nums))     # attributes/methods of a list object
help(list.append)    # documentation for the append method

## Built-in Data Structures

### Lists
colors = ["red", "green", "blue"]
colors.insert(1, "yellow")
print(colors)
print(colors[-1])       # last element
colors.pop()
print(colors)
print("green" in colors)

### Tuples
coordinates = (12.5, 45.7, "NYC")
print(coordinates[2])
lat, lon, city = coordinates   # unpacking
print(city, lat, lon)
print(len(coordinates))

### Sets
even = {2, 4, 6, 8}
odd = {1, 3, 5, 7}
combined = even.union(odd)
print(combined)
print(even.isdisjoint(odd))   # True, no overlap
even.discard(4)
print(even)

### Dictionaries
book = {"title": "Dune", "author": "Frank Herbert", "year": 1965}
print(book.get("author"))
book["genre"] = "Sci-Fi"
print(book)
for key in book:
    print(key, "->", book[key])

## Writing Scripts
# Save as calculator.py and run: python3 calculator.py
def main():
    total = 10 + 20
    print("The total is:", total)

if __name__ == "__main__":
    main()

## Indentation
score = 85
if score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")   # this block executes
    print("Good job!")
else:
    print("Keep trying")
print("Grading complete")

## Tabs vs Spaces
# Mixing tabs and spaces raises a TabError in Python 3.
# Stick to 4 spaces per level consistently:
def check_status(active):
    if active:
        print("Status: Active")
    else:
        print("Status: Inactive")

## Writing Functions
def multiply(a, b):
    """Returns the product of a and b."""
    return a * b

def introduce(name, age=18):   # default argument
    return f"{name} is {age} years old."

print(multiply(6, 7))
print(introduce("Maya"))
print(introduce("Leo", 25))

## Object Basics

### Defining Classes
class Car:
    def __init__(self, make, model):
        self.make = make
        self.model = model

    def drive(self):
        return f"The {self.make} {self.model} is driving."

### Using Objects
car1 = Car("Toyota", "Corolla")
car2 = Car("Tesla", "Model 3")
print(car1.drive())
print(car2.make, car2.model)

### Static vs Instance Variables
class Employee:
    company_name = "TechCorp"   # static/class variable — shared

    def __init__(self, name, salary):
        self.name = name        # instance variable — unique
        self.salary = salary

e1 = Employee("Anna", 50000)
e2 = Employee("Sam", 60000)
print(e1.name, e1.salary)
print(e2.name, e2.salary)
print(e1.company_name, e2.company_name)  # same for both